### ISSUE TITLE
Landscape

### ISSUE THREAD

**Issue by rominator1983** [Codeuctivity/PuppeteerSharp.Renderer#13]
Hi,

I'd like to create landscape output. How would I do that using the CLI?

Kind regards

**Comment by stesee** [comment]
That's currently not configurable using the cli. PuppeteerSharp seems to support it, https://www.puppeteersharp.com/api/PuppeteerSharp.PdfOptions.html ... It would be easy to add a cli parameter to enable landscape and a PR with such a change is welcome.
