### ISSUE TITLE
The released exe only works with windows

### ISSUE THREAD

**Issue by rominator1983** [Codeuctivity/PuppeteerSharp.Renderer#28]
It would be great to have an executable for linux as well.
Maybe a framework-dependent App (.dll) would be a compromise for not having multiple publishing profiles? In https://learn.microsoft.com/en-us/dotnet/core/deploying/ it is stated that dotnet publish can provide a .dll and a .exe for the current platform (or probably that of the publishing profile) in the same step.

**Comment by stesee** [comment]
Please test https://github.com/Codeuctivity/PuppeteerSharp.Renderer/releases/download/latest-prerelease/Codeuctivity.HtmlRendererCli.Portable.zip .
