### ISSUE TITLE
when code reaches Renderer.CreateAsync() application Stops

### ISSUE THREAD

**Issue by yoosefheidari** [Codeuctivity/PuppeteerSharp.Renderer#33]
i want to convert html to pdf but when code reachs to this line :
await using var chromiumRenderer = await Renderer.CreateAsync();
application will stop working

**Comment by stesee** [comment]
Please add more details. Which version, os, bittness, .net version do you use? Can you add some minimal reproduceable?

**Comment by brunbimmer** [comment]
I am having the same problem, but I am logging the error:

Running as root with --no-sandbox is not supported. 

How do we use the Codeuctivity Renderer and apply the above parameter to allow me to run this in a docker container?

**Comment by stesee** [comment]
You can disable sandboxing in the latest version using:

```
 using (var chromiumRenderer = await Renderer.CreateAsync(new BrowserFetcher(), "--no-sandbox"))
            {
                await chromiumRenderer.ConvertHtmlToPng(sourceHtmlFilePath, actualFilePath);
            }
```

I am curious. What does `cat /proc/version` show on your system?

**Comment by brunbimmer** [comment]
@stesee Thank you for the update and the code drop was to potentially fix the issue. Unfortunately, this didn't seem to work. I am still getting the same error, so it is like the launch options didn't make it down to the appropriate layer.

**Comment by brunbimmer** [comment]
@stesee 

Forgot to provide the following from  cat /proc/version

Linux version 3.10.0-1160.80.1.el7.x86_64 ([mockbuild@x86-vm-41.build.eng.bos.redhat.com](mailto:mockbuild@x86-vm-41.build.eng.bos.redhat.com)) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Sat Oct 8 18:13:21 UTC 2022

**Comment by brunbimmer** [comment]
@stesee  I am working in a possible fix for this. will do a PR once I test it locally and in our Kubernetes environment.

**Comment by brunbimmer** [comment]
@stesee Seems like I am unable to create a branch or generate a Pull Request. You might need to set me up as a Contributor (i.e., handle is brunbimmer).

**Comment by stesee** [comment]
You can create [a fork and create pull requests from there](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork). Joining into a project and getting a role assigned is some steps after that.

**Comment by brunbimmer** [comment]
Excellent, wasn't aware of this approach.

Thank you
Paul

**Comment by brunbimmer** [comment]
@stesee All good to go and waiting for your review to approve

**Comment by brunbimmer** [comment]
@stesee Just pulled in the latest release to verify the LaunchOptions parameter. I must have not noticed it before when you updated, so this is good and will allow me to perform the function that I need to perform. without altering the baseline code.

I am still curious about the security implication though? What was the concern?

**Comment by stesee** [comment]
I can not explain it better/shorter than: https://stackoverflow.com/questions/66998228/why-is-no-sandbox-a-unsafe-arg-in-puppeteer ... and further references.
